apiVersion: audit.k8s.io/v1
kind: Policy
# exclude resources where the body is security-sensitive
- level: Metadata
  namespace: oauth-server
  name: oauth-server
  labels:
    app: oauth-server
  resources:
    - group: "route.openshift.io"
      resources: ["routes"]
    - resources: ["secrets"]
- level: Metadata
  resources:
    - group: "oauth.openshift.io"
      resources: ["oauthclients"]
# log request and response payloads for all write requests
- level: RequestResponse
  verbs:
    - update
    - patch
    - create
    - delete
    - deletecollection
# catch-all rule to log all other requests at the Metadata level.
- level: Metadata
  # Long-running requests like watches that fall under this rule will not
  # generate an audit event in RequestReceived.
  omitStages:
    - RequestReceived