apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: oauth-server
  name: oauth-server
  labels:
    apps: oauth-server
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  selector:
    matchLabels:
      app: oauth-server